### PR TITLE
REPL support

### LINKED ISSUE #27: Basic REPL support

### LINKED ISSUE #33: Add a dev source set by default
To go along with #27, we should provide a dev source set that will be on the classpath for the repl (and similar tasks).

### PR DESCRIPTION
**Pull request by ajoberstar**
Fixes #27  and Fixes #33

### CODE REVIEW

**Comment by camechis** [comment]
Awesome, this is probably the last feature I need to start trying it out

**Comment by ajoberstar** [comment]
Agreed, this does feel like that last piece for it to be generally useful.

**Comment by aadrian** [comment]
@ajoberstar Very nice, but now it would be cool if Cursive @cmf would recognize this automatically :) .

**Comment by ajoberstar** [comment]
@aadrian Indeed it would. I think the classpath is configured wrong at this point. Haven't had time to think too much about it, but it's including the source set output which means you couldn't live edit your code and refresh the namespaces. Will still want output for things like Java, but want the source for Clojure.

**Comment by ajoberstar** [comment]
I think I have the classpath working correctly. I was able to do some testing with Atom's proto-repl connected to the Gradle nrepl and it seemed to be working (assuming I was using tools.namespace 0.3.0 alphas).

**Comment by ajoberstar** [comment]
Not sure how to write tests for this though.

**Comment by ajoberstar** [comment]
This is ready to review now. Since I can't use stdin through Gradle's test kit I don't have a way to test the REPL in our suite, but did some manual testing.

I pushed out 0.3.0-rc.1 with this branches changes.

There are also updated docs in this branch.

**Comment by ajoberstar** [comment]
And rc.2 coming out  now. Found a couple issues testing with Atom's proto-repl. BTW, will have a PR open with them soon to integrate Gradle support.

**Comment by ajoberstar** [comment]
Certainly welcome feedback if anyone takes a look later, but merging in for now.

**Pull request merged**
