### PR TITLE
Remove support for fail on reflection

### PR DESCRIPTION
**Pull request by ajoberstar**
This gets a little more complicated to implement with the worker API,
 though still doable. As far as I can tell, lein and boot do not support
 failing on reflection, so it at least wouldn't put us behind them.

### CODE REVIEW

**Comment by ajoberstar** [comment]
Hi, @cmf. Since you had this in the old plugin, I assume it served some purpose for you. What are your thoughts on removing the "fail on reflection" feature?

I think I could still make it work with the worker API, just wasn't sure what the use case is.

**Comment by cursive-ide** [comment]
Yes, this is pretty critical for me. Since I'm programming against the IntelliJ API, when I compile against a new version I want the build to fail if a method call can't be resolved, which generally means the API has changed. Not sure that's a common use case, but I probably wouldn't upgrade to a version which didn't support this.

**Comment by jszakmeister** [comment]
I could also see myself using that feature for performance critical code.

**Comment by ajoberstar** [comment]
Makes sense. I'll put something together for the worker API to get this working again.

**Pull request closed without merging**
