### PR TITLE
Figwheel

### PR DESCRIPTION
**Pull request by ajoberstar**
## Context

Adding Figwheel support (through figwheel.main). This provides a good default ClojureScript development experience. Figwheel will be included with the `clojurescript` plugin, but not `clojurescript-base`. 

This involved reworking the configuration approach for compiler options on both Clojure and ClojureScript to use a "builds" concept similar to what you have with lein-cljsbuild (from what I understand).

The reflection warnings config was also simplified from 3 booleans to an enum with 3 options:
- `silent` (default) equivalent of old `reflectionWarnings { enabled = false }`
- `warn` (default) equivalent of old `reflectionWarnings { enabled = true }`
- `fail` (default) equivalent of old `reflectionWarnings { enabled = true; asErrors=true; projectOnly = true }`

Previously, you were allowed to fail your build if your libraries caused a reflection warning. That seemed like a pretty uncommon thing to need, since you don't have much control over that. However, it could be added back as a 4th enum, if needed.

**Related issues:** #29

### Remaining Steps

- [x] Write CLJS builds into the nREPL, so they're available for figwheel
- [x] Update documentation to show new "builds" configuration style

## Contributor Checklist

- [x] Review [Contributing Guidelines](https://github.com/gradle-clojure/gradle-clojure/blob/master/.github/CONTRIBUTING.md).
- [x] Commits contain discrete changes, messages include context about why the change was made and reference the relevant issues.
- [x] Provide functional tests. (under `modules/gradle-clojure-plugin/src/compatTest`)
- [x] Update documentation for user-facing changes. (under `docs/`)
- [x] Ensure all verification tasks pass locally. (`./gradlew check`)
- [ ] Ensure CI builds pass on all Java versions. (watch for commit statuses once the PR is opened)

  **TIP:** If troubleshooting a CI failure, look for the build scan URL near the bottom of the Gradle output.

### CODE REVIEW

**Comment by aadrian** [comment]
Very nice :) !


The used EDN Java library is in a pretty abandoned state however.

**Comment by ajoberstar** [comment]
@aadrian As far as I can tell there aren't any other options for writing edn from Java. Unless maybe Transit (which I haven't looked much into) would be an option for this type of communication.

**Comment by aadrian** [comment]
> As far as I can tell there aren't any other options for writing edn from Java.

We had this problem in other projects too (in fact many JVM projects could be greatly simplified by using EDN).

IMHO the best strategy would be just to fork the project, to be able to do some releases and required updates.

**Comment by ajoberstar** [comment]
What are some of the unresolved issues? So far it seems to be doing the job for our use case.

**Comment by aadrian** [comment]
> What are some of the unresolved issues? 

In order to be useful in the many JVM projects, the the community offered to fix/improve but it did not worked out.

Few of the outstanding issues:
 - a more recent release would be required (the changes are in the development branch)
 - Java 8 support
 - fully and correctly support the EDN format
 - documentation/examples
 - common usage API
 - groovy wrapper
 - another test framework would be needed since Caliper was abandoned by Google too.

Just to mention a few

**Comment by ajoberstar** [comment]
Not sure what you mean by Java 8 support, I'm running it on 8, 9, and 10 for our test suite.

Speaking for myself, I'd rather we didn't start maintaining an EDN library. Until we run into an issue for the plugin's EDN usage, it seems like a moot point though.

**Pull request merged**
